controller_manager_ns: 'controller_manager'
controller_list:
  - name: iiwa/PositionJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  # - name: iiwa/wsg_50_gl
  #   action_ns: gripper_cmd
  #   type:  GripperCommand
  #   default: true
  #   joints:
  #     - wsg50_gripper_left_joint

  # - name: iiwa/wsg_50_gr
  #   action_ns: gripper_cmd
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - wsg50_gripper_right_joint
