######################################################################################################################
## This config file copied from universal_robot/ur_gazebo/config/arm_controller.yaml && joint_state_controller.yaml ##
## Edited by: Vishnuprasad Prachandabhanu                                                                           ##
######################################################################################################################
#panda control parameters:
  panda_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  PositionJointInterface_panda_arm_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.05
      panda_joint1: {trajectory: 0.1, goal: 0.05}
      panda_joint2: {trajectory: 0.1, goal: 0.05}
      panda_joint3: {trajectory: 0.1, goal: 0.05}
      panda_joint4: {trajectory: 0.1, goal: 0.05}
      panda_joint5: {trajectory: 0.1, goal: 0.05}
      panda_joint6: {trajectory: 0.1, goal: 0.05}
      panda_joint7: {trajectory: 0.1, goal: 0.05}
    stop_trajectory_duration: 0.5
    state_publish_rate: 50
    action_monitor_rate: 10
