omronld_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

omronld_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['left_wheel']
  right_wheel: ['right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

  cmd_vel_timeout: 0.5

  base_frame_id: base_link

  enable_odom_tf: false

  estimate_velocity_from_position: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.14159   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3.0 # rad/s^2
