controller_list:
  - name: fake_iiwa_arm_controller
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: fake_iiwa_gripper_controller
    joints:
      - wsg50_gripper_left_joint
      - wsg50_gripper_right_joint
  - name: fake_ur5_arm_controller
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
  - name: fake_panda_arm_controller
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_panda_hand_controller
    joints:
      - panda_finger_joint1